spring:
  application:
    name: axoniq
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/fitnesslab
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.oliverzihler.ch/realms/fitnesslab
          jwk-set-uri: https://auth.oliverzihler.ch/realms/fitnesslab/protocol/openid-connect/certs
axon:
  serializer:
    events: jackson
wix:
  token: ${WIX_TOKEN:default-token-here}
  site:
    id: ${WIX_SITE_ID:default-site-id-here}
  api:
    url: "https://www.wixapis.com/pricing-plans/v3/plans/query"
bexio:
  api:
    token: ${BEXIO_API_TOKEN:default-token-here}
  contact:
    type:
      id: 2
  user:
    id: 1
  owner:
    id: ${BEXIO_OWNER_ID:default-owner-id-here}
