server:
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:axoniq}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fitnesslab}
    username: ${SPRING_DATASOURCE_USERNAME:test}
    password: ${SPRING_DATASOURCE_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE:false}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:https://auth.oliverzihler.ch/realms/fitnesslab}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:https://auth.oliverzihler.ch/realms/fitnesslab/protocol/openid-connect/certs}
axon:
  serializer:
    events: jackson
wix:
  token: ${WIX_TOKEN:default-token-here}
  site:
    id: ${WIX_SITE_ID:default-site-id-here}
  api:
    url: "https://www.wixapis.com/pricing-plans/v3/plans/query"
bexio:
  api:
    token: ${BEXIO_API_TOKEN:default-token-here}
  contact:
    type:
      id: 2
  user:
    id: 1
  owner:
    id: ${BEXIO_OWNER_ID:default-owner-id-here}
